FROM ubuntu:22.04

# if you need a proxy , exec "docker build  -t {image} . --network host"
# or remove it.
ENV http_proxy http://192.168.1.101:1080
ENV https_proxy http://192.168.1.101:1080

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install curl git  apt-transport-https gnupg  software-properties-common -y && curl --silent https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add - \
    && curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && add-apt-repository --yes --no-update "deb https://dl.yarnpkg.com/debian/ stable main" \
    && apt update && apt install python3 python3-dev python3-virtualenv \
    build-essential libssl-dev libgdal-dev libgeos-dev \
    gdal-bin libxml2-dev libxslt1-dev zlib1g-dev libjpeg-turbo8-dev \
    postgresql-client libmagic-dev yarn python3-mapscript \
    libqgis-dev qt5-image-formats-plugins build-essential cmake -y \
    && mkdir -p /opt/nextgis/config /opt/nextgis/data /opt/nextgis/package  /opt/nextgis/dist \
    && virtualenv -p /usr/bin/python3 /opt/nextgis/env \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && unset http_proxy && unset https_proxy

ENV http_proxy  ""
ENV https_proxy  ""