FROM ubuntu:22.04

# if you need a proxy , exec "docker build  -t {image} . --network host"
# or remove it.
ENV http_proxy http://192.168.1.101:1080
ENV https_proxy http://192.168.1.101:1080

ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt install python3 python3-dev python3-virtualenv \
    build-essential libssl-dev libgdal-dev libgeos-dev \
    gdal-bin libxml2-dev libxslt1-dev zlib1g-dev libjpeg-turbo8-dev \
    postgresql-client libmagic-dev python3-mapscript \
    libqgis-dev qt5-image-formats-plugins build-essential cmake -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get remove --auto-remove -y python3-pip \
    && unset http_proxy && unset https_proxy

ENV http_proxy  ""
ENV https_proxy  ""