version: "3.9" 
services:
  app:
    image: vinsonws/nextgisweb:latest
    container_name: app
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ../../data:/opt/nextgis/data
      - ../../config:/opt/nextgis/config
    ports:
      - "8000:8080"
