name: Docker Image CI

on:
  schedule:
    - cron:  '0 12 15 * *'

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    environment: DOCKER_ACCOUNT
    steps:
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.TOKEN }}
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag vinsonws/nextgisweb:$(date +%Y%m%d)

    - name: Push
      run: | 
        docker push vinsonws/nextgisweb:$(date +%Y%m%d)
        docker tag vinsonws/nextgisweb:$(date +%Y%m%d) vinsonws/nextgisweb:latest
        docker push vinsonws/nextgisweb:latest
